name: Publish to Github Pages
on:
  push:
    branches: [main]
  # Allows workflow to be triggered manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout/@v4
      - name: Create extension index for OB 2.0
        run: |
            jq -s 'reduce .[] as $item ({}; . * $item)' $(find ./v2 -type f -name "*.json") > build/obv2p0.json
      - name: Create extension index for OB 3.0
        run: |
            jq -s 'reduce .[] as $item ({}; . * $item)' $(find ./v3 -type f -name "*.json") > build/obv3p0.json
      - name: Publish to GH Pages
        uses: w3c/spec-prod@v2
        with:
            GH_PAGES_BRANCH: gh-pages